version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile # Should match your Dockerfile's path
    ports:
      - "8080:80"
    environment:
      - ConnectionStrings__SqlServerConnStr=Server=sql-server,1434;Database=PropLandDB;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True;
    depends_on:
      - sql-server

  sql-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong!Passw0rd
    ports:
      - "1434:1433"
